FROM python:3.12.3-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt update -y && \
    apt install -y --no-install-recommends \
        wget vim unzip zip curl tzdata iputils-ping telnet git openssh-client pkg-config xmlsec1 libxml2-dev libxmlsec1-dev libxmlsec1-openssl gcc && \ 
    rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt .
RUN pip --no-cache-dir install -r requirements.txt

WORKDIR /workspace

CMD [ "bash" ]
