# Generated by Django 5.0.3 on 2024-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('events', models.JSONField(blank=True, default=list)),
                ('trace_id', models.BigIntegerField(blank=True, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('node_id', models.CharField(blank=True, max_length=256, null=True)),
                ('egress_tcp_num', models.BigIntegerField(blank=True, null=True)),
                ('egress_thread_id', models.BigIntegerField(blank=True, null=True)),
                ('ingress_tcp_num', models.BigIntegerField(blank=True, null=True)),
                ('ingress_thread_id', models.BigIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['trace_id'], name='dist_tracin_trace_i_592c62_idx')],
                'index_together': {('date_created',)},
            },
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('span_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cluster'], name='dist_tracin_cluster_dde883_idx'), models.Index(fields=['name'], name='dist_tracin_name_f42f81_idx')],
                'index_together': {('start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.UUIDField()),
                ('timestamp', models.DateTimeField()),
                ('tcp_seq_num', models.BigIntegerField()),
                ('thread_id', models.BigIntegerField()),
                ('ingress', models.BooleanField()),
                ('node_id', models.CharField(max_length=256)),
                ('span_exists', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'index_together': {('date_created',)},
            },
        ),
    ]
