# Generated by Django 5.0.7 on 2024-08-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dist_tracing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Span',
        ),
        migrations.DeleteModel(
            name='Trace',
        ),
        migrations.DeleteModel(
            name='Traffic',
        ),
    ]
