# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alaz-backend-request-writer
  name: alaz-backend-request-writer-deployment
  namespace: anteon-staging
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alaz-backend-request-writer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-04-11T01:46:57+03:00"
      creationTimestamp: null
      labels:
        app: alaz-backend-request-writer
        appType: ddosify
    spec:
      containers:
      - command:
        - /workspace/start_scripts/start_request_writer.sh
        envFrom:
        - secretRef:
            name: alaz-backend-env
        image: ddosify/cloud_alaz_backend:latest
        imagePullPolicy: Always
        name: backend
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-registry-anteon
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
