# Generated by Django 5.0.3 on 2024-06-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='from_uid_statefulset',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='to_uid_statefulset',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
