# Generated by Django 5.0.3 on 2024-06-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_request_from_uid_statefulset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='from_uid_statefulset',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='to_uid_statefulset',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
