# Generated by Django 5.0.3 on 2024-06-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_connection_from_uid_statefulset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='non_simplified_path',
            field=models.CharField(blank=True, max_length=1248),
        ),
    ]
