# Generated by Django 5.0.3 on 2024-06-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_request_non_simplified_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
