# Generated by Django 5.0.3 on 2024-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_connection_id_alter_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cluster', models.UUIDField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('latency', models.BigIntegerField()),
                ('from_ip', models.CharField(max_length=15)),
                ('to_ip', models.CharField(max_length=15)),
                ('from_port', models.PositiveIntegerField()),
                ('to_port', models.PositiveIntegerField()),
                ('from_uid_pod', models.UUIDField(blank=True, null=True)),
                ('from_uid_service', models.UUIDField(blank=True, null=True)),
                ('from_uid_deployment', models.UUIDField(blank=True, null=True)),
                ('from_uid_daemonset', models.UUIDField(blank=True, null=True)),
                ('from_uid_statefulset', models.UUIDField(blank=True, null=True)),
                ('to_uid_pod', models.UUIDField(blank=True, null=True)),
                ('to_uid_service', models.UUIDField(blank=True, null=True)),
                ('to_url_outbound', models.CharField(blank=True, max_length=1024, null=True)),
                ('to_uid_deployment', models.UUIDField(blank=True, null=True)),
                ('to_uid_daemonset', models.UUIDField(blank=True, null=True)),
                ('to_uid_statefulset', models.UUIDField(blank=True, null=True)),
                ('topic', models.CharField(max_length=100)),
                ('partition', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=100)),
                ('encrypted', models.BooleanField(default=False)),
                ('tcp_seq_num', models.BigIntegerField(blank=True, null=True)),
                ('node_id', models.CharField(blank=True, max_length=100, null=True)),
                ('thread_id', models.BigIntegerField(blank=True, null=True)),
                ('span_exists', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cluster'], name='core_kafkae_cluster_678378_idx')],
                'index_together': {('start_time',)},
            },
        ),
    ]
