# Generated by Django 5.0.3 on 2024-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kafkaevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkaevent',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
