# Generated by Django 5.0.3 on 2024-07-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_kafkaevent_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='heartbeat_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
