# Generated by Django 5.0.3 on 2024-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cluster_heartbeat_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='alert_messages',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='setting',
            name='bloat_notifier_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
