# Generated by Django 5.0.7 on 2024-08-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_request_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafkaevent',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='kafkaevent',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='kafkaevent',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='kafkaevent',
            name='span_exists',
        ),
        migrations.RemoveField(
            model_name='kafkaevent',
            name='tcp_seq_num',
        ),
        migrations.RemoveField(
            model_name='kafkaevent',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='span_exists',
        ),
        migrations.RemoveField(
            model_name='request',
            name='tcp_seq_num',
        ),
        migrations.RemoveField(
            model_name='request',
            name='thread_id',
        ),
    ]
