# Generated by Django 5.0.7 on 2024-08-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_kafkaevent_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kafkaevent',
            old_name='encrypted',
            new_name='tls',
        ),
    ]
