# Generated by Django 5.0.7 on 2024-08-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_encrypted_kafkaevent_tls'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.UUIDField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(max_length=100)),
                ('namespace', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('uid', models.UUIDField()),
                ('reason', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('count', models.PositiveIntegerField()),
                ('first_timestamp', models.DateTimeField()),
                ('last_timestamp', models.DateTimeField()),
            ],
        ),
    ]
